version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - nimble-net
    restart: always

  frontend:
    build:
      context: ./frontend
    image: frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nimble-net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd@1234
      POSTGRES_DB: chat
    ports:
      - "5433:5432"
    networks:
      - nimble-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - nimble-net

networks:
  nimble-net:
    driver: bridge